version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: miniBlog
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  # контейнер для работы демонов вебсокетов и очередей
#  demon:
#    build:
#      context: .
#      dockerfile: php.dockerfile
#    container_name: demon
#    volumes:
#      - ./src:/var/www/html:delegated
#    ports:
#      - "6001:6001"
#    depends_on:
#      - mysql
#    working_dir: /var/www/html
#    user: laravel
#    entrypoint: ['php', '/var/www/html/artisan']
#    networks:
#      - laravel

#  demon:
#    build:
#      context: .
#      dockerfile: ubuntu.dockerfile
#    container_name: demon
#    volumes:
#      - ./src:/home/src
#    working_dir: /home/src
#    ports:
#      - "6001:6001"
#    networks:
#      - laravel
#    entrypoint: ["/bin/bash"]


  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "8000:8000"
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "6001:6001"
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel